texto= open('ascii.txt','w')
texto.seek(0)
texto.write("""codigo ascii 00 = NULL ( Carácter nulo )
codigo ascii 01 = SOH ( Inicio de encabezado )
codigo ascii 02 = STX ( Inicio de texto )
codigo ascii 03 = ETX ( Fin de texto, palo corazon barajas inglesas de poker )
codigo ascii 04 = EOT ( Fin de transmisión, palo diamantes barajas de poker )
codigo ascii 05 = ENQ ( Consulta, palo treboles barajas inglesas de poker )
codigo ascii 06 = ACK ( Reconocimiento, palo picas cartas de poker )
codigo ascii 07 = BEL ( Timbre )
codigo ascii 08 = BS ( Retroceso )
codigo ascii 09 = HT ( Tabulador horizontal )
codigo ascii 10 = LF ( Nueva línea - salto de línea )
codigo ascii 11 = VT ( Tabulador vertical )
codigo ascii 12 = FF ( Nueva página - salto de página )
codigo ascii 13 = CR ( ENTER - retorno de carro )
codigo ascii 14 = SO ( Desplazamiento hacia afuera )
codigo ascii 15 = SI ( Desplazamiento hacia adentro )
codigo ascii 16 = DLE ( Escape de vínculo de datos )
codigo ascii 17 = DC1 ( Control dispositivo 1 )
codigo ascii 18 = DC2 ( Control dispositivo 2 )
codigo ascii 19 = DC3 ( Control dispositivo 3 )
codigo ascii 20 = DC4 ( Control dispositivo 4 )
codigo ascii 21 = NAK ( Confirmación negativa )
codigo ascii 22 = SYN ( Inactividad síncronica )
codigo ascii 23 = ETB ( Fin del bloque de transmisión )
codigo ascii 24 = CAN ( Cancelar )
codigo ascii 25 = EM ( Fin del medio )
codigo ascii 26 = SUB ( Sustitución )
codigo ascii 27 = ESC ( Esc - escape )
codigo ascii 28 = FS ( Separador de archivos )
codigo ascii 29 = GS ( Separador de grupos )
codigo ascii 30 = RS ( Separador de registros )
codigo ascii 31 = US ( Separador de unidades )
codigo ascii 127 = DEL ( DEL - Suprimir, borrar, eliminar )
codigo ascii 32 = espacio ( Espacio en blanco )
codigo ascii 33 = !
codigo ascii 34 = "
codigo ascii 35 = #
codigo ascii 36 = $
codigo ascii 37 = %
codigo ascii 38 = &
codigo ascii 39 = '
codigo ascii 40 = (
codigo ascii 41 = )
codigo ascii 42 = *
codigo ascii 43 = +
codigo ascii 44 = ,
codigo ascii 45 = -
codigo ascii 46 = .
codigo ascii 47 = /
codigo ascii 48 = 0
codigo ascii 49 = 1
codigo ascii 50 = 2
codigo ascii 51 = 3
codigo ascii 52 = 4
codigo ascii 53 = 5
codigo ascii 54 = 6
codigo ascii 55 = 7
codigo ascii 56 = 8
codigo ascii 57 = 9
codigo ascii 58 = :
codigo ascii 59 = ;
codigo ascii 60 = <
codigo ascii 61 = =
codigo ascii 62 = >
codigo ascii 63 = ?
codigo ascii 64 = @
codigo ascii 65 = A
codigo ascii 66 = B
codigo ascii 67 = C
codigo ascii 68 = D
codigo ascii 69 = E
codigo ascii 70 = F
codigo ascii 71 = G
codigo ascii 72 = H
codigo ascii 73 = I
codigo ascii 74 = J
codigo ascii 75 = K
codigo ascii 76 = L
codigo ascii 77 = M
codigo ascii 78 = N
codigo ascii 79 = O
codigo ascii 80 = P
codigo ascii 81 = Q
codigo ascii 82 = R
codigo ascii 83 = S
codigo ascii 84 = T
codigo ascii 85 = U
codigo ascii 86 = V
codigo ascii 87 = W
codigo ascii 88 = X
codigo ascii 89 = Y
codigo ascii 90 = Z
codigo ascii 91 = [
codigo ascii 92 = \
codigo ascii 93 = ]
codigo ascii 94 = ^
codigo ascii 95 = _
codigo ascii 96 = `
codigo ascii 97 = a
codigo ascii 98 = b
codigo ascii 99 = c
codigo ascii 100 = d
codigo ascii 101 = e
codigo ascii 102 = f
codigo ascii 103 = g
codigo ascii 104 = h
codigo ascii 105 = i
codigo ascii 106 = j
codigo ascii 107 = k
codigo ascii 108 = l
codigo ascii 109 = m
codigo ascii 110 = n
codigo ascii 111 = o
codigo ascii 112 = p
codigo ascii 113 = q
codigo ascii 114 = r
codigo ascii 115 = s
codigo ascii 116 = t
codigo ascii 117 = u
codigo ascii 118 = v
codigo ascii 119 = w
codigo ascii 120 = x
codigo ascii 121 = y
codigo ascii 122 = z
codigo ascii 123 = {
codigo ascii 124 = |
codigo ascii 125 = }
codigo ascii 126 = ~
codigo ascii 128 = Ç
codigo ascii 129 = ü
codigo ascii 130 = é
codigo ascii 131 = â
codigo ascii 132 = ä
codigo ascii 133 = à
codigo ascii 134 = å
codigo ascii 135 = ç
codigo ascii 136 = ê
codigo ascii 137 = ë
codigo ascii 138 = è
codigo ascii 139 = ï
codigo ascii 140 = î
codigo ascii 141 = ì
codigo ascii 142 = Ä
codigo ascii 143 = Å
codigo ascii 144 = É
codigo ascii 145 = æ
codigo ascii 146 = Æ
codigo ascii 147 = ô
codigo ascii 148 = ö
codigo ascii 149 = ò
codigo ascii 150 = û
codigo ascii 151 = ù
codigo ascii 152 = ÿ
codigo ascii 153 = Ö
codigo ascii 154 = Ü
codigo ascii 155 = ø
codigo ascii 156 = £
codigo ascii 157 = Ø
codigo ascii 158 = ×
codigo ascii 159 = ƒ
codigo ascii 160 = á 
codigo ascii 161 = í
codigo ascii 162 = ó
codigo ascii 163 = ú
codigo ascii 164 = ñ
codigo ascii 165 = Ñ
codigo ascii 166 = ª
codigo ascii 167 = º
codigo ascii 168 = ¿
codigo ascii 169 = ®
codigo ascii 170 = ¬
codigo ascii 171 = ½
codigo ascii 172 = ¼
codigo ascii 173 = ¡
codigo ascii 174 = «
codigo ascii 175 = »
codigo ascii 181 = Á
codigo ascii 182 = Â
codigo ascii 183 = À
codigo ascii 184 = ©
codigo ascii 189 = ¢
codigo ascii 190 = ¥
codigo ascii 224 = Ó
codigo ascii 225 = ß
codigo ascii 226 = Ô
codigo ascii 227 = Ò
codigo ascii 228 = õ
codigo ascii 229 = Õ
codigo ascii 230 = µ
codigo ascii 231 = þ
codigo ascii 232 = Þ
codigo ascii 233 = Ú
codigo ascii 234 = Û
codigo ascii 235 = Ù
codigo ascii 236 = ý
codigo ascii 237 = Ý
codigo ascii 238 = ¯
codigo ascii 239 = ´
codigo ascii 241 = ±
codigo ascii 243 = ¾
codigo ascii 244 = ¶
codigo ascii 245 = §
codigo ascii 246 = ÷
codigo ascii 247 = ¸
codigo ascii 248 = °
codigo ascii 249 = ¨
codigo ascii 250 = ·
codigo ascii 251 = ¹
codigo ascii 252 = ³
codigo ascii 253 = ²
""")
texto.close()
